project_id = "xoymllyfwvbnbxsbbinu"

[functions.receive-booking]
verify_jwt = false

[functions.receive-subscription]
verify_jwt = false

[functions.login-by-phone]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.sync-to-external]
verify_jwt = false

[functions.sync-to-external]
verify_jwt = false
